[package]
name = "minimetro"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.0", features = [] }
bevy_2d_line = "0.1.4"
bevy_tweening = "0.13.0"
cgmath = "0.18.0"
rand = "0.9.1"

[features]
wayland = ["bevy/wayland"]
